volumes:
  prosjekt-postgresql:

services:

  postgres:
    container_name: prosjekt-postgres
    image: 'postgis/postgis:16-3.4-alpine'
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - prosjekt-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TYPEORM_USER}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
