version: 2.1

commands:
  install:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  format_check:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install
      - run: npx nx format:check

  build_api:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install
      - run:
          name: Build api
          command: npx nx run api:build

  affected_test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install
      - run:
          name: Run test affected projects
          command: npx nx affected --base=main --head=$CIRCLE_SHA1 -t lint test --exclude *-e2e

  affected_e2e:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - install
      - run:
          name: Setup daemons
          command: |
            cp .env.test .env
            docker compose up -d
      - run:
          name: Run e2e on affected projects
          command: npx nx affected --base=main --head=$CIRCLE_SHA1 -t e2e

workflows:
  api:
    jobs:
      - build_api:
          filters:
            branches:
              only: main

  affected:
    jobs:
      - format_check
      - affected_test
          # filters:
          #   branches:
          #     ignore:
          #       - main
      - affected_e2e
          # filters:
          #   branches:
          #     ignore:
          #       - main
