volumes:
  prosjekt-postgresql:

networks:
  prosjekt:

services:

  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./apps/api/dockerfile
    networks:
      - prosjekt
    env_file: .env
    environment:
      TYPEORM_HOST: "postgres"

  postgres:
    container_name: prosjekt-postgres
    image: 'postgis/postgis:16-3.4-alpine'
    command: -p ${TYPEORM_PORT}
    volumes:
      - prosjekt-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TYPEORM_USER}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - prosjekt
